% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %
% Title:        Class Exam Score Puzzle                     %
% Author:       Ron J. Guglielmone Jr.                      %
% Date:         September 25, 2017                          %
%                                                           %
% Description:  Given exam scores and a mean, all encoded   %
%               as letters, determine which number (0 - 9)  %
%               is mapped to each letter (a - j).  These    %
%               scores came from my girlfriend's finance    %
%               class at UC Berkeley.                       %
% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %

clear all;
close all;

% We know these two because all three digit scores start with
% 1 _ _ and the top score possible was 1 0 5:
C = 0;
F = 1;

numbers = [2 3 4 5 6 7 8 9];     % Remaining numbers.
allPerms = perms(numbers);       % All possible permutations.

% Get size of set:
heightA = size(allPerms);
height = heightA(1);

% Iterate through each permutation:
for i = 1 : height
    
    % Assign numbers to letters:
    A = allPerms(i,1);
    B = allPerms(i,2);
    D = allPerms(i,3);
    E = allPerms(i,4);
    G = allPerms(i,5);
    H = allPerms(i,6);
    I = allPerms(i,7);
    J = allPerms(i,8);
    
    % Calculate resulting scores:
    scores = [
        G*10+G       J*10+C       A*10+G       F*100+C*10+C ...
        F*100+C*10+I G*10+B       G*10+A       G*10+G       ...
        E*10+C       A*10+F	      G*10+F	   A*10+E       ...
        D*10+D       G*10+G       G*10+J       D*10+E       ...
        G*10+H       A*10+I       F*100+C*10+I G*10+J       ...
        G*10+J       G*10+B       G*10+I       A*10+I       ...
        A*10+G       G*10+I       A*10+J       G*10+B       ...
        F*100+C*10+B G*10+I       D*10+C       F*100+C*10+F ...
        A*10+A       F*100+C*10+J G*10+B       G*10+I       ...
        A*10+E       A*10+J       G*10+I       E*10+B       ...
        A*10+G       A*10+H       E*10+H       G*10+A       ...
        D*10+J       D*10+H       E*10+F       A*10+A       ...
        G*10+C       G*10+J       G*10+G       G*10+D       ...
        G*10+J       A*10+G       G*10+F       F*100+C*10+B ...
        G*10+A	     A*10+G	      E*10+J	   G*10+I       ...
        A*10+H	     A*10+H	      G*10+E       G*10+C       ...
        A*10+G       E*10+F       G*10+J       G*10+B       ...
        G*10+B       G*10+E       A*10+D       G*10+B       ...
        E*10+J       J*10+C       A*10+B       G*10+G       ...
        G*10+A       D*10+A       G*10+A       G*10+D       ...
        A*10+J       A*10+A       G*10+E       A*10+C       ...
        G*10+A       G*10+C       G*10+J       D*10+E       ...
        D*10+J       G*10+G       G*10+G       A*10+J       ...
        I*10+D       D*10+B       D*10+D       G*10+I       ...
        A*10+I       G*10+H       G*10+E       A*10+F       ...
        A*10+A       D*10+H       G*10+F       A*10+I       ...
        D*10+C       A*10+B       G*10+I       G*10+A       ...
        A*10+G       G*10+I       A*10+A       G*10+C       ...
        A*10+D       G*10+A       G*10+B       A*10+E       ...
        A*10+J       A*10+G       A*10+H       A*10+I       ...
        D*10+H       D*10+E       G*10+A       F*100+C*10+C ...
        D*10+J       G*10+C       A*10+H       D*10+B       ...
        D*10+C       E*10+H       G*10+F       A*10+H       ...
        A*10+G       G*10+I       G*10+G       A*10+D       ...
        G*10+E       G*10+E       G*10+E       A*10+C       ...
        G*10+I];
    
    % Calculate the mean:
    length = size(scores);
    length = length(2);
    realAvg = sum(scores)/length;
    
    % Calculate the 'given' mean:
    avrg = A*10+D + C*(10^-1) + ...
        I*(10^-2) + ...
        J*(10^-3) + ...
        H*(10^-4) + ...
        E*(10^-5) + ...
        F*(10^-6);
    
    % Round each to 3 decimals:
    avrg = round(avrg,3);
    realAvg = round(realAvg,3);
    
    % Check for valid solution:
    if realAvg == avrg
        A
        B
        C
        D
        E
        F
        G
        H
        I
        J
        break
    end
    
end


